export const semanticsDark = {
  color: {
    bg: {
      root: 'var(--aw-ref-color-neutral-950)',
      surface: 'var(--aw-ref-color-neutral-900)',
      'surface-raised': 'var(--aw-ref-color-neutral-800)',
      'surface-overlay': 'var(--aw-ref-color-neutral-700)',
      brand: 'var(--aw-ref-color-maroon-500)',
      'brand-subtle': 'var(--aw-ref-color-maroon-800)',
    },
    text: {
      primary: 'var(--aw-ref-color-neutral-100)',
      secondary: 'var(--aw-ref-color-neutral-400)',
      muted: 'var(--aw-ref-color-neutral-500)',
      inverse: 'var(--aw-ref-color-neutral-950)',
      brand: 'var(--aw-ref-color-maroon-300)',
      accent: 'var(--aw-ref-color-amber-500)',
    },
    interactive: {
      DEFAULT: 'var(--aw-ref-color-amber-500)',
      hover: 'var(--aw-ref-color-amber-400)',
      active: 'var(--aw-ref-color-amber-600)',
      muted: 'var(--aw-ref-color-amber-800)',
    },
    border: {
      default: 'var(--aw-ref-color-neutral-700)',
      strong: 'var(--aw-ref-color-neutral-500)',
      interactive: 'var(--aw-ref-color-amber-500)',
      brand: 'var(--aw-ref-color-maroon-400)',
    },
    feedback: {
      error: 'var(--aw-ref-color-red-500)',
      'error-text': 'var(--aw-ref-color-red-300)',
      success: 'var(--aw-ref-color-green-500)',
      'success-text': 'var(--aw-ref-color-green-300)',
      warning: 'var(--aw-ref-color-yellow-500)',
      'warning-text': 'var(--aw-ref-color-yellow-300)',
      info: 'var(--aw-ref-color-blue-500)',
      'info-text': 'var(--aw-ref-color-blue-300)',
    },
    selection: { bg: 'var(--aw-ref-color-amber-900)' },
    focus: { ring: 'var(--aw-ref-color-amber-500)' },
  },
  type: {
    display: {
      size: 'var(--aw-ref-font-size-3xl)',
      'line-height': 'var(--aw-ref-line-height-3xl)',
      weight: 'var(--aw-ref-font-weight-bold)',
      tracking: 'var(--aw-ref-letter-spacing-normal)',
      transform: 'var(--aw-ref-text-transform-uppercase)',
    },
    heading: {
      size: 'var(--aw-ref-font-size-lg)',
      'line-height': 'var(--aw-ref-line-height-lg)',
      weight: 'var(--aw-ref-font-weight-bold)',
      tracking: 'var(--aw-ref-letter-spacing-wide)',
      transform: 'var(--aw-ref-text-transform-uppercase)',
    },
    subheading: {
      size: 'var(--aw-ref-font-size-md)',
      'line-height': 'var(--aw-ref-line-height-md)',
      weight: 'var(--aw-ref-font-weight-medium)',
      tracking: 'var(--aw-ref-letter-spacing-wide)',
      transform: 'var(--aw-ref-text-transform-uppercase)',
    },
    body: {
      size: 'var(--aw-ref-font-size-md)',
      'line-height': 'var(--aw-ref-line-height-md)',
      weight: 'var(--aw-ref-font-weight-regular)',
      tracking: 'var(--aw-ref-letter-spacing-normal)',
    },
    label: {
      size: 'var(--aw-ref-font-size-sm)',
      'line-height': 'var(--aw-ref-line-height-sm)',
      weight: 'var(--aw-ref-font-weight-medium)',
      tracking: 'var(--aw-ref-letter-spacing-wider)',
      transform: 'var(--aw-ref-text-transform-uppercase)',
    },
    caption: {
      size: 'var(--aw-ref-font-size-xs)',
      'line-height': 'var(--aw-ref-line-height-xs)',
      weight: 'var(--aw-ref-font-weight-regular)',
      tracking: 'var(--aw-ref-letter-spacing-normal)',
    },
  },
  space: {
    inset: {
      xs: 'var(--aw-ref-space-1)',
      sm: 'var(--aw-ref-space-2)',
      md: 'var(--aw-ref-space-3)',
      lg: 'var(--aw-ref-space-5)',
      xl: 'var(--aw-ref-space-6)',
    },
    gap: {
      xs: 'var(--aw-ref-space-1)',
      sm: 'var(--aw-ref-space-2)',
      md: 'var(--aw-ref-space-3)',
      lg: 'var(--aw-ref-space-5)',
      xl: 'var(--aw-ref-space-6)',
    },
    layout: {
      xs: 'var(--aw-ref-space-5)',
      sm: 'var(--aw-ref-space-6)',
      md: 'var(--aw-ref-space-7)',
      lg: 'var(--aw-ref-space-8)',
      xl: 'var(--aw-ref-space-9)',
    },
  },
  size: {
    compact: '24px',
    default: '28px',
    comfortable: '36px',
    large: '44px',
    icon: { sm: '12px', md: '16px', lg: '20px' },
  },
  shape: {
    radius: 'var(--aw-ref-radius-none)',
  },
  border: {
    default: 'var(--aw-ref-border-width-thin) var(--aw-ref-border-style-solid) var(--aw-sys-color-border-default)',
    strong: 'var(--aw-ref-border-width-thin) var(--aw-ref-border-style-solid) var(--aw-sys-color-border-strong)',
    interactive: 'var(--aw-ref-border-width-medium) var(--aw-ref-border-style-solid) var(--aw-sys-color-border-interactive)',
    dashed: 'var(--aw-ref-border-width-thin) var(--aw-ref-border-style-dashed) var(--aw-sys-color-border-default)',
  },
  elevation: {
    flat: 'var(--aw-sys-color-bg-surface)',
    raised: 'var(--aw-sys-color-bg-surface-raised)',
    overlay: 'var(--aw-sys-color-bg-surface-overlay)',
  },
  z: {
    default: 'var(--aw-ref-z-base)',
    dropdown: 'var(--aw-ref-z-dropdown)',
    sticky: 'var(--aw-ref-z-sticky)',
    overlay: 'var(--aw-ref-z-overlay)',
    modal: 'var(--aw-ref-z-modal)',
  },
  state: {
    disabled: 'var(--aw-ref-opacity-disabled)',
    hover: 'var(--aw-ref-opacity-hover)',
    pressed: 'var(--aw-ref-opacity-pressed)',
    scrim: 'var(--aw-ref-opacity-overlay)',
  },
  transition: {
    fast: '100ms ease-out',
    none: '0ms',
  },
} as const

export const semanticsLight = {
  color: {
    bg: {
      root: 'var(--aw-ref-color-neutral-50)',
      surface: 'var(--aw-ref-color-neutral-0)',
      'surface-raised': 'var(--aw-ref-color-neutral-100)',
      'surface-overlay': 'var(--aw-ref-color-neutral-200)',
      brand: 'var(--aw-ref-color-maroon-500)',
      'brand-subtle': 'var(--aw-ref-color-maroon-100)',
    },
    text: {
      primary: 'var(--aw-ref-color-neutral-900)',
      secondary: 'var(--aw-ref-color-neutral-600)',
      muted: 'var(--aw-ref-color-neutral-400)',
      inverse: 'var(--aw-ref-color-neutral-50)',
      brand: 'var(--aw-ref-color-maroon-600)',
      accent: 'var(--aw-ref-color-amber-700)',
    },
    interactive: {
      DEFAULT: 'var(--aw-ref-color-amber-700)',
      hover: 'var(--aw-ref-color-amber-600)',
      active: 'var(--aw-ref-color-amber-800)',
      muted: 'var(--aw-ref-color-amber-100)',
    },
    border: {
      default: 'var(--aw-ref-color-neutral-200)',
      strong: 'var(--aw-ref-color-neutral-400)',
      interactive: 'var(--aw-ref-color-amber-700)',
      brand: 'var(--aw-ref-color-maroon-400)',
    },
    feedback: {
      error: 'var(--aw-ref-color-red-500)',
      'error-text': 'var(--aw-ref-color-red-500)',
      success: 'var(--aw-ref-color-green-500)',
      'success-text': 'var(--aw-ref-color-green-500)',
      warning: 'var(--aw-ref-color-yellow-500)',
      'warning-text': 'var(--aw-ref-color-yellow-500)',
      info: 'var(--aw-ref-color-blue-500)',
      'info-text': 'var(--aw-ref-color-blue-500)',
    },
    selection: { bg: 'var(--aw-ref-color-amber-100)' },
    focus: { ring: 'var(--aw-ref-color-amber-600)' },
  },
} as const
